# file: haproxy.cfg
# https://cbonte.github.io/haproxy-dconv/2.3/configuration.html#2.5
defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    http-request set-path /forbidden if { path_beg /flag }
    default_backend servers

backend servers
    server server1 gunicorn:5000 maxconn 32
